apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Chart.Name }}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: '{{ .Chart.Name }}:latest'
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: '{{ .Values.s2iImage.name }}:{{ .Values.s2iImage.tag }}'
  postCommit: {}
  source:
    type: Git
    git:
      uri: {{ .Values.git.uri }}
      ref: {{ .Values.git.branch }}
  triggers:
    - type: ConfigChange
  runPolicy: Serial
